name: gen_license
description: A sample command-line application.
version: 0.1.0+1
homepage: https://github.com/woodemi/gen_license

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  prompts: ^1.3.1
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  gen_license:
